- name: Deploy Dockerized Application
  hosts: production
  tasks:
    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present

    - name: Pull the Docker image
      command: docker pull <docker-hub-username>/rest-app:latest

    - name: Stop existing container
      command: docker stop rest-app || true

    - name: Remove existing container
      command: docker rm rest-app || true

    - name: Run the new container
      command: >
        docker run -d --name rest-app -p 8080:8080 <docker-hub-username>/rest-app:latest
